source 'https://rubygems.org'

ruby '3.3.3'

# -- Gemfile --

gem 'minitest'
gem 'rubocop', group: 'development', require: false
gem 'sorbet', :group => :development
gem 'sorbet-runtime'
gem 'tapioca', require: false, :group => [:development, :test]
