name: FizzBuzz Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-fizzbuzz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run FizzBuzz
        run: docker compose exec fizz_buzz bash "./workflow.sh"
